name:                upcheck
version:             0.0.0.0
github:              "NorfairKing/upcheck"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - http-client
  - http-client-tls
  - http-types
  - network-uri
  - pretty-show
  - retry
  - sydtest
  - text
  - yaml
  - yamlparse-applicative

executables:
  upcheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - upcheck
