name:                upcheck
version:             0.0.0.0
github:              "NorfairKing/upcheck"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

extra-source-files:
- options.nix

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-nix
  - autodocodec-yaml
  - bytestring
  - http-client
  - http-client-tls
  - http-types
  - network-uri
  - path
  - path-io
  - pretty-show
  - retry
  - sydtest
  - text
  - yaml

executables:
  upcheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - upcheck


tests:
  upscheck-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - autodocodec-nix
    - upcheck
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - iproute
    - sydtest
    - text
